#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Feb 01, 2016 08:48:05 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.lab62
    set site_3_0 $base.lab71
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 736x584+690+108
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1680 1001
    wm minsize $top 120 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "SH Mobot Configuration"
    vTcl:DefineAlias "$top" "SHParaToplevel" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Blur 
    vTcl:DefineAlias "$top.lab48" "Label2" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text {Canny Lo} 
    vTcl:DefineAlias "$top.lab49" "Label3" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text {Canny Hi} 
    vTcl:DefineAlias "$top.lab50" "Label4" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Saturation 
    vTcl:DefineAlias "$top.lab51" "Label5" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text Brightness 
    vTcl:DefineAlias "$top.lab52" "Label6" vTcl:WidgetProc "SHParaToplevel" 1
    labelframe $top.lab62 \
        -foreground black -text Connection -background {#d9d9d9} -height 145 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 380 
    vTcl:DefineAlias "$top.lab62" "Labelframe1" vTcl:WidgetProc "SHParaToplevel" 1
    set site_3_0 $top.lab62
    label $site_3_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {IP ADDR} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label7" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text PORT 
    vTcl:DefineAlias "$site_3_0.lab68" "Label8" vTcl:WidgetProc "SHParaToplevel" 1
    entry $site_3_0.ent37 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent37" "IPEntry" vTcl:WidgetProc "SHParaToplevel" 1
    entry $site_3_0.ent38 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent38" "PortEntry" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu37 \
        -command pingAction -takefocus {} -text Ping 
    vTcl:DefineAlias "$site_3_0.tBu37" "PingButton" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu38 \
        -command connectAction -takefocus {} -text Connect 
    vTcl:DefineAlias "$site_3_0.tBu38" "ConnectButton" vTcl:WidgetProc "SHParaToplevel" 1
    place $site_3_0.lab67 \
        -in $site_3_0 -x 10 -y 20 -width 53 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 10 -y 50 -width 53 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent37 \
        -in $site_3_0 -x 70 -y 20 -width 294 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent38 \
        -in $site_3_0 -x 70 -y 50 -width 294 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu37 \
        -in $site_3_0 -x 290 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.tBu38 \
        -in $site_3_0 -x 290 -y 110 -anchor nw -bordermode ignore 
    labelframe $top.lab71 \
        -foreground black -text {System Status} -background {#d9d9d9} \
        -height 145 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 280 
    vTcl:DefineAlias "$top.lab71" "Labelframe2" vTcl:WidgetProc "SHParaToplevel" 1
    set site_3_0 $top.lab71
    ttk::progressbar $site_3_0.tPr47
    vTcl:DefineAlias "$site_3_0.tPr47" "TProgressbar1" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Battery: 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Unknown 
    vTcl:DefineAlias "$site_3_0.lab49" "Label9" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {System Integrity:} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label10" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Unknown 
    vTcl:DefineAlias "$site_3_0.lab51" "Label11" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Signal Strength:} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label12" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text Unknown 
    vTcl:DefineAlias "$site_3_0.lab53" "Label13" vTcl:WidgetProc "SHParaToplevel" 1
    place $site_3_0.tPr47 \
        -in $site_3_0 -x 20 -y 50 -width 240 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 20 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 70 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 20 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 120 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 20 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 120 -y 110 -anchor nw -bordermode ignore 
    ttk::scale $top.tSc42 \
        -to 50 -takefocus {} 
    vTcl:DefineAlias "$top.tSc42" "BlurScale" vTcl:WidgetProc "SHParaToplevel" 1
    bind $top.tSc42 <ButtonRelease-1> {
        lambda e: settingsChanged(e)
    }
    ttk::scale $top.tSc43 \
        -to 300 -takefocus {} 
    vTcl:DefineAlias "$top.tSc43" "CannyLoScale" vTcl:WidgetProc "SHParaToplevel" 1
    bind $top.tSc43 <ButtonRelease-1> {
        lambda e: settingsChanged(e)
    }
    ttk::scale $top.tSc44 \
        -to 300 -takefocus {} 
    vTcl:DefineAlias "$top.tSc44" "CannyHiScale" vTcl:WidgetProc "SHParaToplevel" 1
    bind $top.tSc44 <ButtonRelease-1> {
        lambda e: settingsChanged(e)
    }
    ttk::scale $top.tSc45 \
        -to 100 -takefocus {} 
    vTcl:DefineAlias "$top.tSc45" "SaturationScale" vTcl:WidgetProc "SHParaToplevel" 1
    bind $top.tSc45 <ButtonRelease-1> {
        lambda e: settingsChanged(e)
    }
    ttk::scale $top.tSc46 \
        -to 100 -takefocus {} 
    vTcl:DefineAlias "$top.tSc46" "BrightnessScale" vTcl:WidgetProc "SHParaToplevel" 1
    bind $top.tSc46 <ButtonRelease-1> {
        lambda e: settingsChanged(e)
    }
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu54 \
        -command applyAction -takefocus {} -text Apply 
    vTcl:DefineAlias "$top.tBu54" "ApplyButton" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $top.tCh57 \
        -variable MedianBlurBool -takefocus {} -text {Median Blur} 
    vTcl:DefineAlias "$top.tCh57" "MedianBlurCheck" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $top.tCh58 \
        -variable LineApproxBool -takefocus {} -text {Line Approx.} 
    vTcl:DefineAlias "$top.tCh58" "LineApproxCheck" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu59 \
        -command previewAction -takefocus {} -text Preview 
    vTcl:DefineAlias "$top.tBu59" "PreviewButton" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab37 \
        -background {#a0a0a0} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {No Signal} 
    vTcl:DefineAlias "$top.lab37" "ProcessedImageLabel" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab38 \
        -background {#a0a0a0} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {No Signal} 
    vTcl:DefineAlias "$top.lab38" "OriginalImageLabel" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab39 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Original Image} 
    vTcl:DefineAlias "$top.lab39" "Label16" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab40 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Processed Image} 
    vTcl:DefineAlias "$top.lab40" "Label17" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab41 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Computer Vision} 
    vTcl:DefineAlias "$top.lab41" "Label18" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab42 \
        -background {#a0a0a0} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {No Signal} 
    vTcl:DefineAlias "$top.lab42" "CVImageLabel" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu44 \
        -command emergencyStopAction -takefocus {} -text {Emergency Stop} 
    vTcl:DefineAlias "$top.tBu44" "StopButton" vTcl:WidgetProc "SHParaToplevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 10 -y 190 -width 65 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab49 \
        -in $top -x 10 -y 230 -width 67 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab50 \
        -in $top -x 10 -y 270 -width 63 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab51 \
        -in $top -x 10 -y 310 -width 63 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab52 \
        -in $top -x 10 -y 350 -width 63 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab62 \
        -in $top -x 20 -y 10 -width 380 -height 145 -anchor nw \
        -bordermode ignore 
    place $top.lab71 \
        -in $top -x 420 -y 10 -width 280 -height 145 -anchor nw \
        -bordermode ignore 
    place $top.tSc42 \
        -in $top -x 80 -y 190 -width 290 -anchor nw -bordermode ignore 
    place $top.tSc43 \
        -in $top -x 80 -y 230 -width 290 -anchor nw -bordermode ignore 
    place $top.tSc44 \
        -in $top -x 80 -y 270 -width 290 -anchor nw -bordermode ignore 
    place $top.tSc45 \
        -in $top -x 80 -y 310 -width 290 -anchor nw -bordermode ignore 
    place $top.tSc46 \
        -in $top -x 80 -y 350 -width 290 -anchor nw -bordermode ignore 
    place $top.tBu54 \
        -in $top -x 380 -y 350 -anchor nw -bordermode ignore 
    place $top.tCh57 \
        -in $top -x 380 -y 190 -anchor nw -bordermode ignore 
    place $top.tCh58 \
        -in $top -x 380 -y 270 -anchor nw -bordermode ignore 
    place $top.tBu59 \
        -in $top -x 380 -y 320 -anchor nw -bordermode ignore 
    place $top.lab37 \
        -in $top -x 260 -y 410 -width 214 -height 161 -anchor nw \
        -bordermode ignore 
    place $top.lab38 \
        -in $top -x 20 -y 410 -width 214 -height 161 -anchor nw \
        -bordermode ignore 
    place $top.lab39 \
        -in $top -x 20 -y 380 -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 260 -y 380 -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 500 -y 380 -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 500 -y 410 -width 214 -height 161 -anchor nw \
        -bordermode ignore 
    place $top.tBu44 \
        -in $top -x 530 -y 220 -width 126 -height 115 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

