#! /usr/bin/env python
#
# Support module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Feb 01, 2016 08:48:10 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global MedianBlurBool
    MedianBlurBool = StringVar()

    global LineApproxBool
    LineApproxBool = StringVar()


def applyAction():
    print('UI_Mobot_Configuration_support.applyAction')
    sys.stdout.flush()

def emergencyStopAction():
    print('UI_Mobot_Configuration_support.emergencyStopAction')
    sys.stdout.flush()

def previewAction():
    print('UI_Mobot_Configuration_support.previewAction')
    sys.stdout.flush()

def settingsChanged(p1):
    print('UI_Mobot_Configuration_support.settingsChanged')
    sys.stdout.flush()

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


