#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Feb 21, 2016 06:00:50 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import panel_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('SH_Mobot_Preview')
    geom = "1123x366+522+115"
    root.geometry(geom)
    w = SH_Mobot_Preview (root)
    panel_support.init(root, w)
    root.mainloop()

w = None
def create_SH_Mobot_Preview(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('SH_Mobot_Preview')
    geom = "1123x366+522+115"
    w.geometry(geom)
    w_win = SH_Mobot_Preview (w)
    panel_support.init(w, w_win, param)
    return w_win

def destroy_SH_Mobot_Preview():
    global w
    w.destroy()
    w = None


class SH_Mobot_Preview:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background="#d9d9d9")


        self.V1 = Label(master)
        self.V1.place(relx=0.03, rely=0.08, height=120, width=160)
        self.V1.configure(background="#d4d4d4")
        self.V1.configure(disabledforeground="#a3a3a3")
        self.V1.configure(foreground="#000000")
        self.V1.configure(text='''No Signal''')
        self.V1.configure(width=214)

        self.V2 = Label(master)
        self.V2.place(relx=0.19, rely=0.08, height=120, width=160)
        self.V2.configure(background="#d4d4d4")
        self.V2.configure(disabledforeground="#a3a3a3")
        self.V2.configure(foreground="#000000")
        self.V2.configure(text='''No Signal''')

        self.V3 = Label(master)
        self.V3.place(relx=0.35, rely=0.08, height=120, width=160)
        self.V3.configure(background="#d4d4d4")
        self.V3.configure(disabledforeground="#a3a3a3")
        self.V3.configure(foreground="#000000")
        self.V3.configure(text='''No Signal''')

        self.V4 = Label(master)
        self.V4.place(relx=0.51, rely=0.08, height=120, width=160)
        self.V4.configure(background="#d4d4d4")
        self.V4.configure(disabledforeground="#a3a3a3")
        self.V4.configure(foreground="#000000")
        self.V4.configure(text='''No Signal''')

        self.V5 = Label(master)
        self.V5.place(relx=0.03, rely=0.52, height=120, width=160)
        self.V5.configure(background="#d4d4d4")
        self.V5.configure(disabledforeground="#a3a3a3")
        self.V5.configure(foreground="#000000")
        self.V5.configure(text='''No Signal''')

        self.V6 = Label(master)
        self.V6.place(relx=0.19, rely=0.52, height=120, width=160)
        self.V6.configure(background="#d4d4d4")
        self.V6.configure(disabledforeground="#a3a3a3")
        self.V6.configure(foreground="#000000")
        self.V6.configure(text='''No Signal''')

        self.V7 = Label(master)
        self.V7.place(relx=0.35, rely=0.52, height=120, width=160)
        self.V7.configure(background="#d4d4d4")
        self.V7.configure(disabledforeground="#a3a3a3")
        self.V7.configure(foreground="#000000")
        self.V7.configure(text='''No Signal''')

        self.V8 = Label(master)
        self.V8.place(relx=0.51, rely=0.52, height=120, width=160)
        self.V8.configure(background="#d4d4d4")
        self.V8.configure(disabledforeground="#a3a3a3")
        self.V8.configure(foreground="#000000")
        self.V8.configure(text='''No Signal''')

        self.VL1 = Label(master)
        self.VL1.place(relx=0.06, rely=0.44, height=21, width=81)
        self.VL1.configure(background=_bgcolor)
        self.VL1.configure(disabledforeground="#a3a3a3")
        self.VL1.configure(foreground="#000000")
        self.VL1.configure(text='''Original Video''')

        self.VL2 = Label(master)
        self.VL2.place(relx=0.23, rely=0.44, height=21, width=59)
        self.VL2.configure(background=_bgcolor)
        self.VL2.configure(disabledforeground="#a3a3a3")
        self.VL2.configure(foreground="#000000")
        self.VL2.configure(text='''Processed''')

        self.VL3 = Label(master)
        self.VL3.place(relx=0.39, rely=0.44, height=21, width=59)
        self.VL3.configure(background=_bgcolor)
        self.VL3.configure(disabledforeground="#a3a3a3")
        self.VL3.configure(foreground="#000000")
        self.VL3.configure(text='''Processed''')

        self.VL4 = Label(master)
        self.VL4.place(relx=0.55, rely=0.44, height=21, width=59)
        self.VL4.configure(background=_bgcolor)
        self.VL4.configure(disabledforeground="#a3a3a3")
        self.VL4.configure(foreground="#000000")
        self.VL4.configure(text='''Processed''')

        self.VL5 = Label(master)
        self.VL5.place(relx=0.07, rely=0.87, height=21, width=59)
        self.VL5.configure(background=_bgcolor)
        self.VL5.configure(disabledforeground="#a3a3a3")
        self.VL5.configure(foreground="#000000")
        self.VL5.configure(text='''Processed''')

        self.VL6 = Label(master)
        self.VL6.place(relx=0.23, rely=0.87, height=21, width=59)
        self.VL6.configure(background=_bgcolor)
        self.VL6.configure(disabledforeground="#a3a3a3")
        self.VL6.configure(foreground="#000000")
        self.VL6.configure(text='''Processed''')

        self.VL7 = Label(master)
        self.VL7.place(relx=0.39, rely=0.87, height=21, width=59)
        self.VL7.configure(background=_bgcolor)
        self.VL7.configure(disabledforeground="#a3a3a3")
        self.VL7.configure(foreground="#000000")
        self.VL7.configure(text='''Processed''')

        self.VL8 = Label(master)
        self.VL8.place(relx=0.55, rely=0.87, height=21, width=59)
        self.VL8.configure(background=_bgcolor)
        self.VL8.configure(disabledforeground="#a3a3a3")
        self.VL8.configure(foreground="#000000")
        self.VL8.configure(text='''Processed''')

        self.S1 = ttk.Scale(master)
        self.S1.place(relx=0.71, rely=0.08, relwidth=0.27, relheight=0.0
                , height=26)
        self.S1.configure(to="100")
        self.S1.configure(length="300")
        self.S1.configure(takefocus="")
        self.S1.bind('<ButtonRelease-1>',lambda e:panel_support.updateValue(e))

        self.S2 = ttk.Scale(master)
        self.S2.place(relx=0.71, rely=0.22, relwidth=0.27, relheight=0.0
                , height=26)
        self.S2.configure(to="100")
        self.S2.configure(length="300")
        self.S2.configure(takefocus="")
        self.S2.bind('<ButtonRelease-1>',lambda e:panel_support.updateValue(e))

        self.S3 = ttk.Scale(master)
        self.S3.place(relx=0.71, rely=0.36, relwidth=0.27, relheight=0.0
                , height=26)
        self.S3.configure(to="100")
        self.S3.configure(length="300")
        self.S3.configure(takefocus="")
        self.S3.bind('<ButtonRelease-1>',lambda e:panel_support.updateValue(e))

        self.S4 = ttk.Scale(master)
        self.S4.place(relx=0.71, rely=0.49, relwidth=0.27, relheight=0.0
                , height=26)
        self.S4.configure(to="100")
        self.S4.configure(length="300")
        self.S4.configure(takefocus="")
        self.S4.bind('<ButtonRelease-1>',lambda e:panel_support.updateValue(e))

        self.S5 = ttk.Scale(master)
        self.S5.place(relx=0.71, rely=0.63, relwidth=0.27, relheight=0.0
                , height=26)
        self.S5.configure(to="100")
        self.S5.configure(length="300")
        self.S5.configure(takefocus="")
        self.S5.bind('<ButtonRelease-1>',lambda e:panel_support.updateValue(e))

        self.S6 = ttk.Scale(master)
        self.S6.place(relx=0.71, rely=0.77, relwidth=0.27, relheight=0.0
                , height=26)
        self.S6.configure(to="100")
        self.S6.configure(length="300")
        self.S6.configure(takefocus="")
        self.S6.bind('<ButtonRelease-1>',lambda e:panel_support.updateValue(e))

        self.SL1 = Label(master)
        self.SL1.place(relx=0.67, rely=0.08, height=21, width=18)
        self.SL1.configure(background=_bgcolor)
        self.SL1.configure(disabledforeground="#a3a3a3")
        self.SL1.configure(foreground="#000000")
        self.SL1.configure(text='''S1''')

        self.SL2 = Label(master)
        self.SL2.place(relx=0.67, rely=0.22, height=21, width=18)
        self.SL2.configure(background=_bgcolor)
        self.SL2.configure(disabledforeground="#a3a3a3")
        self.SL2.configure(foreground="#000000")
        self.SL2.configure(text='''S2''')

        self.SL3 = Label(master)
        self.SL3.place(relx=0.67, rely=0.36, height=21, width=18)
        self.SL3.configure(background=_bgcolor)
        self.SL3.configure(disabledforeground="#a3a3a3")
        self.SL3.configure(foreground="#000000")
        self.SL3.configure(text='''S3''')

        self.SL4 = Label(master)
        self.SL4.place(relx=0.67, rely=0.49, height=21, width=18)
        self.SL4.configure(background=_bgcolor)
        self.SL4.configure(disabledforeground="#a3a3a3")
        self.SL4.configure(foreground="#000000")
        self.SL4.configure(text='''S4''')

        self.SL5 = Label(master)
        self.SL5.place(relx=0.67, rely=0.63, height=21, width=18)
        self.SL5.configure(background=_bgcolor)
        self.SL5.configure(disabledforeground="#a3a3a3")
        self.SL5.configure(foreground="#000000")
        self.SL5.configure(text='''S5''')

        self.SL6 = Label(master)
        self.SL6.place(relx=0.67, rely=0.77, height=21, width=18)
        self.SL6.configure(background=_bgcolor)
        self.SL6.configure(disabledforeground="#a3a3a3")
        self.SL6.configure(foreground="#000000")
        self.SL6.configure(text='''S6''')






if __name__ == '__main__':
    vp_start_gui()



